export const equipmentList = {
  c2cr001: {
    nombre: "Chandora Primaria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-CR001",
    tamano: "23x118",
    tonelaje: "118",
    otros: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cr001.jpeg"),
    pdfManual: require("./path/to/file.pdf"),
    pdfPlanos: require("./path/to/file.pdf"),
  },
  c2ml001: {
    nombre: "Molino de Bolas",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-ML001",
    tamano: "23x118",
    tonelaje: "118",
    otros: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2ml001.jpeg"),
    pdfManual: require("./path/to/file.pdf"),
    pdfPlanos: require("./path/to/file.pdf"),
  },
  c2cr021: {
    nombre: "Chandora Secundaria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-CR021",
    tamano: "23x118",
    tonelaje: "118",
    otros: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cr021.jpeg"),
    pdfManual: require("./path/to/file.pdf"),
    pdfPlanos: require("./path/to/file.pdf"),
  },
  c2cv001: {
    nombre: "Faja Transportadora",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-CV001",
    tamano: "23x118",
    tonelaje: "118",
    otros: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cv001.jpeg"),
    pdfManual: require("./path/to/file.pdf"),
    pdfPlanos: require("./path/to/file.pdf"),
  },
  c2sc001: {
    nombre: "Zaranda Vibratoria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-SC001",
    tamano: "23x118",
    tonelaje: "118",
    otros: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2sc001.jpeg"),
    pdfManual: require("./path/to/file.pdf"),
    pdfPlanos: require("./path/to/file.pdf"),
  },
};
