export const equipmentList = [
  {
    nombre: "Reuniones",
    marca: "Reuniones",
    caracteristicas: "85x118",
    tag: "C2-REU",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/reu.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "chancadora",
  },
  {
    nombre: "Chancadora Primaria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-CR001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cr001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "chancadora",
  },
  {
    nombre: "Molino de Bolas",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-ML001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2ml001.jpeg"),

    // image: require("../../assets/equipmentplant/ImageIcons/c2ml001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "molino",
  },
  {
    nombre: "Chancadora Secundaria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-CR021",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cr021.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "chancadora",
  },
  {
    nombre: "Faja Transportadora",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-CV001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cv001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "faja",
  },
  {
    nombre: "Zaranda Vibratoria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C2-SC001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2sc001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "zaranda",
  },
  {
    nombre: "Seguridad",
    marca: "Cerro Verde",
    caracteristicas: "85x118",
    tag: "SEG-C2",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/seguridad.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "seguridad",
  },
  {
    nombre: "Medio Ambiente",
    marca: "Cerro Verde",
    caracteristicas: "85x118",
    tag: "MA-C2",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/medioambiente.png"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "ambiente",
  },
  {
    nombre: "Chancadora Primaria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C1-CR001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cr001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "chancadora",
  },
  {
    nombre: "Molino de Bolas",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C1-ML001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2ml001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "molino",
  },
  {
    nombre: "Chancadora Secundaria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C1-CR021",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cr021.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "chancadora",
  },
  {
    nombre: "Faja Transportadora",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C1-CV001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2cv001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "faja",
  },
  {
    nombre: "Zaranda Vibratoria",
    marca: "FL-Smith",
    caracteristicas: "85x118",
    tag: "C1-SC001",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/c2sc001.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "zaranda",
  },
  {
    nombre: "Seguridad",
    marca: "Cerro Verde",
    caracteristicas: "85x118",
    tag: "SEG-C1",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/seguridad.jpeg"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "seguridad",
  },
  {
    nombre: "Medio Ambiente",
    marca: "Cerro Verde",
    caracteristicas: "85x118",
    tag: "MA-C1",
    tamano: "23x118",
    tonelaje: "118",
    datos_adicionales: "datos adicionales",
    image: require("../../assets/equipmentplant/ImageIcons/medioambiente.png"),
    // pdfManual: require("./path/to/file.pdf"),
    // pdfPlanos: require("./path/to/file.pdf"),
    clase: "ambiente",
  },
];
